name: Auto Update Nodes

on:
  schedule:
    - cron: "0 */6 * * *"   # 每天 00:00 UTC 执行一次（北京时间 08:00）
  workflow_dispatch:      # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python export_nodes_443.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add nodes.txt
          git commit -m "Auto update $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
